language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-24.0.0
    - android-23
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-23
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
script:
  - ./build.sh
