language: android
jdk:
    - oraclejdk8
android:
  components:
    - tools
    - build-tools-24.0.2
    - android-24
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    - addon-google_apis-google-24
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

env:
  - SAMPLE=admob 
  - SAMPLE=analytics 
  - SAMPLE=app-indexing 
  - SAMPLE=auth 
  - SAMPLE=config 
  - SAMPLE=crash 
  - SAMPLE=database 
  - SAMPLE=dynamiclinks 
  - SAMPLE=invites 
  - SAMPLE=messaging 
  - SAMPLE=storage

script:
  - ./build.sh
